version: "3"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:805"
    depends_on:
      - streamlit
    networks:
      - my_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8503"
    networks:
      - my_network

networks:
  my_network:
